name: FMCSwear
main: hu.Pdani.FMCSwear.FMCSwearPlugin
version: '1.1.8'
authors: [Pdani001]
description: FNaFMC swear filter plugin
softdepend: [Skript]
commands:
  fmcswear:
    description: FMCSwear config reload command
    usage: /<command> [args]
    aliases: [fswear,fmcsw]
permissions:
  fmcswear.admin:
    description: Admin permission
    default: op